railroad-ebnf-beta
title "Area light properties"

property = "named" name | "location" point | "axisU" vector | "axisV" vector
         | "steps" number | "uSteps" number | "vSteps" number
         | "seed" number | "no" "jitter" | "color" color ;
