railroad-ebnf-beta
title "Repeating things"

for = ( "for" name "in" ( interval | list ) | "over" interval ) [ "by" expression ]
    "{" { surface } "}" ;
interval = ( "[" | "(" ) expression "," expression ( "]" | ")" ) ;
