using Complex = System.Numerics.Complex;
using MathNet.Numerics;
using RayTracer.Basics;
using RayTracer.Core;
using RayTracer.Extensions;
using RayTracer.Graphics;

namespace RayTracer.Geometry;

/// <summary>
/// This is the surface that represents one path segment (line, quadratic, or cubic curve)
/// of a lathe's 2D profile, revolved around the Y axis.
/// </summary>
public class LathePathSurface
{
    private readonly Polynomial _radius;
    private readonly Polynomial _height;
    private readonly Polynomial _radiusDerivative;
    private readonly Polynomial _heightDerivative;

    public LathePathSurface(IPathSegment segment)
    {
        _radius = BuildPolynomial(segment.Points, point => point.X);
        _height = BuildPolynomial(segment.Points, point => point.Y);
        _radiusDerivative = _radius.Differentiate();
        _heightDerivative = _height.Differentiate();
    }

    /// <summary>
    /// This method converts a Bézier segment's control points (2 for a line, 3 for a
    /// quadratic curve, 4 for a cubic curve) into the equivalent power-basis polynomial in
    /// the curve parameter u, over [0, 1], for a single coordinate component.
    /// </summary>
    /// <param name="points">The segment's control points.</param>
    /// <param name="component">Selects the X or Y component of each control point.</param>
    /// <returns>The polynomial, in ascending order (the constant term first).</returns>
    private static Polynomial BuildPolynomial(TwoDPoint[] points, Func<TwoDPoint, double> component)
    {
        double[] p = points.Select(component).ToArray();

        return p.Length switch
        {
            2 => new Polynomial(p[0], p[1] - p[0]),
            3 => new Polynomial(p[0], 2 * (p[1] - p[0]), p[0] - 2 * p[1] + p[2]),
            4 => new Polynomial(
                p[0], 3 * (p[1] - p[0]), 3 * (p[0] - 2 * p[1] + p[2]), -p[0] + 3 * p[1] - 3 * p[2] + p[3]),
            _ => throw new NotSupportedException(
                $"Lathe profiles don't support path segments with {p.Length} control points.")
        };
    }

    /// <summary>
    /// This method is used to determine any intersections between the given 3D ray and the
    /// surface of revolution generated by spinning this path segment around the Y axis.
    /// The profile segment defines radius(u) and height(u) as polynomials in u over
    /// [0, 1] (degree 1 for a line, 2 for a quadratic curve, 3 for a cubic curve).  A ray
    /// hits the resulting surface where, for some u in [0, 1] and distance t along the
    /// ray:
    ///   (ox + t*dx)^2 + (oz + t*dz)^2 = radius(u)^2
    ///   oy + t*dy = height(u)
    /// </summary>
    /// <param name="surface">The surface we are supporting.</param>
    /// <param name="ray">The 3D ray we are evaluating.</param>
    /// <returns>An enumeration of the intersections found with this segment.</returns>
    public IEnumerable<Intersection> GetIntersections(Surface surface, Ray ray)
    {
        return Math.Abs(ray.Direction.Y) < DoubleExtensions.Epsilon
            ? GetIntersectionsForHorizontalRay(surface, ray)
            : GetIntersectionsForGeneralRay(surface, ray);
    }

    /// <summary>
    /// This method handles the common case where the ray's Y direction is non-zero, so the
    /// height equation can be solved for t directly as a polynomial in u: t(u) =
    /// (height(u) - oy) / dy.  Substituting that into the radius equation collapses the
    /// problem down to a single polynomial in u (degree 2 for a line, 4 for a quadratic
    /// curve, 6 for a cubic curve), solved via MathNet.Numerics' general polynomial root
    /// finder rather than a hand-rolled formula per degree.
    /// </summary>
    private IEnumerable<Intersection> GetIntersectionsForGeneralRay(Surface surface, Ray ray)
    {
        double ox = ray.Origin.X, oy = ray.Origin.Y, oz = ray.Origin.Z;
        double dx = ray.Direction.X, dy = ray.Direction.Y, dz = ray.Direction.Z;
        Polynomial t = (_height - oy) / dy;
        Polynomial x = ox + dx * t;
        Polynomial z = oz + dz * t;
        Polynomial equation = x * x + z * z - _radius * _radius;

        foreach (Complex root in equation.Roots())
        {
            if (!root.Imaginary.Near(0))
                continue;

            double u = root.Real;

            if (u < -DoubleExtensions.Epsilon || u > 1 + DoubleExtensions.Epsilon)
                continue;

            double distance = t.Evaluate(u);

            if (distance < 0)
                continue;

            yield return CreateIntersection(surface, distance, u, ray.At(distance));
        }
    }

    /// <summary>
    /// This method handles the case where the ray's Y direction is (near) zero.  The
    /// height equation then pins down the candidate value(s) of u directly (as roots of
    /// height(u) - oy = 0, which may have more than one solution for a curved segment).
    /// For each valid u, the radius equation becomes an ordinary circle/ray intersection,
    /// quadratic in t regardless of the segment's own degree.
    /// </summary>
    private IEnumerable<Intersection> GetIntersectionsForHorizontalRay(Surface surface, Ray ray)
    {
        Polynomial heightEquation = _height - ray.Origin.Y;

        foreach (Complex uRoot in heightEquation.Roots())
        {
            if (!uRoot.Imaginary.Near(0))
                continue;

            double u = uRoot.Real;

            if (u < -DoubleExtensions.Epsilon || u > 1 + DoubleExtensions.Epsilon)
                continue;

            double radius = _radius.Evaluate(u);
            double ox = ray.Origin.X, oz = ray.Origin.Z;
            double dx = ray.Direction.X, dz = ray.Direction.Z;
            double a = dx * dx + dz * dz;
            double b = 2 * (ox * dx + oz * dz);
            double c = ox * ox + oz * oz - radius * radius;

            foreach (double t in SolveQuadratic(a, b, c))
            {
                if (t < 0)
                    continue;

                yield return CreateIntersection(surface, t, u, ray.At(t));
            }
        }
    }

    /// <summary>
    /// This method builds the 3D intersection for a solved (t, u) pair, computing the
    /// surface normal by revolving the profile's local 2D tangent -- its derivative at u --
    /// to the angle of the actual hit point around the Y axis.
    /// </summary>
    private Intersection CreateIntersection(Surface surface, double t, double u, Point point)
    {
        double radiusAtHit = Math.Sqrt(point.X * point.X + point.Z * point.Z);
        Vector radial = radiusAtHit.Near(0)
            ? Directions.Right
            : new Vector(point.X / radiusAtHit, 0, point.Z / radiusAtHit);
        double radiusSlope = _radiusDerivative.Evaluate(u);
        double heightSlope = _heightDerivative.Evaluate(u);
        Vector normal = (radial * heightSlope + Directions.Up * -radiusSlope).Unit;

        return new PrecomputedNormalIntersection(surface, t, normal);
    }

    /// <summary>
    /// This method solves a·x^2 + b·x + c = 0, degrading gracefully to a linear solve (or
    /// no solutions) as the leading coefficients vanish.
    /// </summary>
    private static IEnumerable<double> SolveQuadratic(double a, double b, double c)
    {
        if (Math.Abs(a) < DoubleExtensions.Epsilon)
        {
            if (Math.Abs(b) < DoubleExtensions.Epsilon)
                yield break;

            yield return -c / b;
            yield break;
        }

        double discriminant = b * b - 4 * a * c;

        if (discriminant < 0)
            yield break;

        double sqrtDiscriminant = Math.Sqrt(discriminant);

        yield return (-b - sqrtDiscriminant) / (2 * a);

        if (discriminant > 0)
            yield return (-b + sqrtDiscriminant) / (2 * a);
    }
}
