railroad-ebnf-beta
title "Camera"

camera = "camera" "{" { "named" name | "location" point | "look" "at" point | "up" vector
       | "field" "of" "view" angle | "aperture" number
       | "focal" ( "point" point | "distance" number )
       | "blur" "samples" number | "shutter" number | "seed" number } "}" ;
