using System.Text;
using RayTracer.Extensions;

namespace RayTracer.Geometry.LSystems;

/// <summary>
/// This is the base class for each of the supported renderers that will convert the
/// production of an L-system into some form of geometry.
/// </summary>
public abstract class LSystemShapeRenderer
{
    private static readonly Rune Move = new('f');
    private static readonly Rune Draw = new('F');
    private static readonly Rune Leaf = new('~');

    /// <summary>
    /// This field holds the standard rune (character) to turtle command mapping.
    /// </summary>
    private static readonly Dictionary<Rune, TurtleCommand> StandardCommandMapping = new ()
    {
        { Move, TurtleCommand.Move },
        { Draw, TurtleCommand.DrawLine },
        { new Rune('+'), TurtleCommand.TurnLeft },
        { new Rune('-'), TurtleCommand.TurnRight },
        { new Rune('\u2212'), TurtleCommand.TurnRight },
        { new Rune('^'), TurtleCommand.PitchUp },
        { new Rune('\u2227'), TurtleCommand.PitchUp },
        { new Rune('&'), TurtleCommand.PitchDown },
        { new Rune('\\'), TurtleCommand.RollLeft },
        { new Rune('<'), TurtleCommand.RollLeft },
        { new Rune('/'), TurtleCommand.RollRight },
        { new Rune('>'), TurtleCommand.RollRight },
        { new Rune('|'), TurtleCommand.TurnAround },
        { new Rune('$'), TurtleCommand.ToVertical },
        { new Rune('['), TurtleCommand.StartBranch },
        { new Rune(']'), TurtleCommand.CompleteBranch },
        // '{' - Start a polygon.
        // 'G' - Move forward and draw a line; do not record a vertex.
        // '.' - Record a vertex in the current polygon.
        // '}' - Complete a polygon.
        { Leaf, TurtleCommand.Leaf },
        { new Rune('!'), TurtleCommand.DecreaseDiameter }
        // "'" - Increment color index.
        // '%' - Cut off the remainder of the branch.
    };

    /// <summary>
    /// This property returns the set of standard render command runes.
    /// </summary>
    internal static HashSet<Rune> Commands => StandardCommandMapping.Keys
        .Where(cmd => cmd != LSystemProducer.LeftBracket &&
                      cmd != LSystemProducer.RightBracket &&
                      cmd != Move && cmd != Draw && cmd != Leaf)
        .ToHashSet();

    /// <summary>
    /// This property holds the set of controls that dictate how productions from this
    /// L-system are rendered into geometry.
    /// </summary>
    public LSystemRenderingControls RenderingControls { get; set; } = new ();

    /// <summary>
    /// This property holds the map that will be used to convert runes to turtle commands.
    /// </summary>
    public Dictionary<Rune, TurtleCommand> CommandMapping { get; } = new (StandardCommandMapping);

    /// <summary>
    /// This property holds the surfaces generated by a subclass.
    /// </summary>
    internal List<Surface> Surfaces { get; }

    /// <summary>
    /// This property may offer a bounding box the owning group should accept.
    /// </summary>
    internal BoundingBox BoundingBox { get; set; }

    /// <summary>
    /// This property holds the recipe for the leaf surface to stamp down wherever the
    /// production calls for one (the <c>~</c> command).  It is a factory rather than a single
    /// surface because every occurrence needs its own, independently transformed copy, and
    /// because a named leaf surface has to be resolved with a render context this renderer
    /// does not have -- so the resolution is captured at resolve time and simply invoked here.
    /// </summary>
    internal Func<Surface> LeafFactory { get; set; }

    /// <summary>
    /// This property holds the recipe for each surface the production may name after a <c>~</c>,
    /// keyed by the character that names it -- so <c>~L</c> may stamp a leaf where <c>~K</c>
    /// stamps a fruit.  A <c>~</c> that names nothing bound here falls back to
    /// <see cref="LeafFactory"/>.
    /// </summary>
    internal Dictionary<Rune, Func<Surface>> SurfaceFactories { get; } = new ();

    private readonly string _production;
    private readonly Stack<Turtle> _stack;

    protected LSystemShapeRenderer(string production)
    {
        _production = production;
        _stack = new Stack<Turtle>();

        Surfaces = [];
    }

    /// <summary>
    /// This method is used to render the L-system production we were constructed with into
    /// a surface for ray tracing.
    /// </summary>
    internal void Render()
    {
        Turtle turtle = new Turtle(RenderingControls);
        
        _stack.Push(turtle);

        Begin(turtle);

        // We walk the runes by index rather than mapping them straight to commands, because a
        // '~' may name the surface it wants in the rune that follows it, and that one has to be
        // claimed before it is read as a command in its own right.
        Rune[] runes = _production.AsRunes();

        for (int index = 0; index < runes.Length; index++)
        {
            TurtleCommand command = ToTurtleCommand(runes[index]);

            if (command == TurtleCommand.Unknown)
                continue;

            PreExecute(_stack.Peek(), command);

            // A leaf is geometry common to every renderer, so it is stamped here rather than in
            // a subclass's Execute; everything else is the subclass's to handle.
            if (command == TurtleCommand.Leaf)
                StampLeaf(_stack.Peek(), TakeSurfaceFactory(runes, ref index));
            else
                Execute(_stack.Peek(), command);
        }

        Complete(turtle);
    }

    /// <summary>
    /// This method is used to tell the subclass that the rendering to a surface is
    /// starting.
    /// </summary>
    /// <param name="turtle">The initial turtle.  Provided in case the renderer needs to
    /// make any initial adjustments.</param>
    protected virtual void Begin(Turtle turtle) {}

    /// <summary>
    /// This method is used to convert the given rune into a turtle command.
    /// </summary>
    /// <param name="rune">The rune to convert.</param>
    /// <returns>The turtle command the rune translates to.</returns>
    private TurtleCommand ToTurtleCommand(Rune rune)
    {
        return CommandMapping.GetValueOrDefault(rune, TurtleCommand.Unknown);
    }

    /// <summary>
    /// This method decides which surface a <c>~</c> should stamp, claiming the rune that names it
    /// when there is one.  A <c>~</c> takes the rune that follows it only if that rune is actually
    /// bound to a surface; otherwise it stamps the default and leaves the rune alone.  That rule
    /// is what lets a bare <c>~</c> go on meaning "the default surface": a production reading
    /// <c>...~]</c> needs its <c>]</c> left behind to close the branch, and a <c>~</c> that always
    /// claimed the next rune would swallow it.  The cost is that binding a character which also
    /// appears as a command right after a <c>~</c> lets the <c>~</c> claim it; the fix there is to
    /// bind a different character.
    /// </summary>
    /// <param name="runes">The production being walked.</param>
    /// <param name="index">The index of the <c>~</c>, advanced past the name when one is claimed.</param>
    /// <returns>The factory for the surface to stamp.</returns>
    private Func<Surface> TakeSurfaceFactory(Rune[] runes, ref int index)
    {
        if (index + 1 < runes.Length &&
            SurfaceFactories.TryGetValue(runes[index + 1], out Func<Surface> factory))
        {
            index++;

            return factory;
        }

        return LeafFactory;
    }

    /// <summary>
    /// This method is used to provide default handling for some of the turtle commands.
    /// </summary>
    /// <param name="turtle">The current turtle.</param>
    /// <param name="command">The turtle command to handle.</param>
    private void PreExecute(Turtle turtle, TurtleCommand command)
    {
        switch (command)
        {
            case TurtleCommand.Move:
            case TurtleCommand.DrawLine:
                turtle.Move();
                break;
            case TurtleCommand.TurnLeft:
                turtle.Yaw(-1);
                break;
            case TurtleCommand.TurnRight:
                turtle.Yaw(1);
                break;
            case TurtleCommand.PitchUp:
                turtle.Pitch(1);
                break;
            case TurtleCommand.PitchDown:
                turtle.Pitch(-1);
                break;
            case TurtleCommand.RollLeft:
                turtle.Roll(-1);
                break;
            case TurtleCommand.RollRight:
                turtle.Roll(1);
                break;
            case TurtleCommand.TurnAround:
                turtle.TurnAround();
                break;
            case TurtleCommand.ToVertical:
                turtle.PointUp();
                break;
            case TurtleCommand.StartBranch:
                _stack.Push(turtle.Copy());
                break;
            case TurtleCommand.CompleteBranch:
                _stack.Pop();
                break;
            case TurtleCommand.DecreaseDiameter:
                turtle.DecreaseDiameter();
                break;
            case TurtleCommand.Unknown:
            default:
                break;
        }
    }

    /// <summary>
    /// This method should be overridden to handle the given command.
    /// </summary>
    /// <param name="turtle">The current turtle.</param>
    /// <param name="command">The turtle command to handle.</param>
    protected abstract void Execute(Turtle turtle, TurtleCommand command);

    /// <summary>
    /// This method stamps a fresh leaf surface down at the turtle's current position and
    /// orientation.  Unlike a drawn stem, a leaf keeps its own material, so a bare tree still
    /// shows green leaves on its branches.  Because a leaf reaches out past the turtle's own
    /// point, the owning group's bounding box must be widened to admit it: a box built only
    /// from the turtle path would cull rays aimed at the leaf before it was ever tested.
    /// </summary>
    /// <param name="turtle">The current turtle.</param>
    /// <param name="factory">The recipe for the surface to stamp.</param>
    private void StampLeaf(Turtle turtle, Func<Surface> factory)
    {
        if (factory is null)
            return;

        Surface leaf = factory();

        leaf.Transform = turtle.GetPlacementMatrix() * leaf.Transform;

        Surfaces.Add(leaf);

        if (BoundingBox is null)
            return;

        // Fold the leaf's own extent into the box the owning group will accept.  Preparing
        // the leaf here is what lets it report that extent; the group prepares it once more
        // later, which is harmless.  A leaf that is unbounded by nature has no box of its own,
        // and no finite box can safely exclude it, so we drop ours -- matching the way a
        // Group refuses to bound itself around an unbounded child.
        leaf.PrepareForRendering();

        if (leaf.BoundingBox is null)
            BoundingBox = null;
        else
            BoundingBox.Add(leaf.BoundingBox.TransformedBy(leaf.Transform));
    }

    /// <summary>
    /// This method is used to tell the subclass that the rendering to a surface is
    /// ending.
    /// </summary>
    /// <param name="turtle">The current turtle.</param>
    protected virtual void Complete(Turtle turtle) {}
}
