railroad-ebnf-beta
title "A text solid"

text = "text" "{" { "text" string | font | layout | kerning | "open" | property } "}" ;

font = "font" name { "," name } [ weight ] [ "italic" ] ;

weight = "thin" | "light" | "regular" | "medium" | "bold" | "black" ;
